"""Add unique constraint to pin_code in ParkingLot

Revision ID: 1c51a37ef67a
Revises: 
Create Date: 2025-09-21 23:03:52.594641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c51a37ef67a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_parking_lot_pin_code", ['pin_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.drop_constraint("uq_parking_lot_pin_code", type_='unique')

    # ### end Alembic commands ###
